### ISSUE TITLE
Lenguaje de programació

### ISSUE THREAD

**Issue by MatteoImbrosciano** [juanmaaf/MoneyController#7]
Hola @juanmaaf, para trabajar en el repositorio primero debes acordar qué lenguaje de programación usaremos en él. 
Había pensado en usar Python, ya que es un lenguaje en el que tengo experiencia y es un lenguaje bastante versátil. 
¿Qué opinas?

**Comment by juanmaaf** [comment]
Pues estoy dudando entre Python, que no tengo mucha experiencia pero ya he hecho proyectos empleándolo, o Go, propuesta del profesor.

**Comment by MatteoImbrosciano** [comment]
Nunca he usado GO

**Comment by juanmaaf** [comment]
Yo tampoco, pero veía interesante considerar la propuesta del profesor para esta asignatura. Igualmente, si prefieres Python, úsalo.

**Comment by juanmaaf** [comment]
Nada, no te preocupes. Está bien Python. Lo domino más que Go igualmente.
